FROM python:latest
WORKDIR /code
ADD requirements.txt requirements.txt
RUN pip install -r requirements.txt
COPY app.py app.py
COPY initial_table.py initial_table.py
COPY menu.py menu.py
CMD ["python", "-u", "app.py"]