from app import add_hero, add_history, add_moto, add_random_battle, date, delete_hero, date

def initiates():
    # 4 - create heroes
    add_hero("Stark","Jon Snow", date(280, 1, 1),False,10)
    add_history(1, "Jon Snow is the bastard son of Eddard Stark, Lord of Winterfell. He has five half-siblings: Robb, Sansa, Arya, Bran, and Rickon Stark. Unaware of the identity of his mother, Jon was raised at Winterfell. At the age of fourteen, he joins the Night's Watch, where he earns the nickname Lord Snow.")
    add_hero("Targaryen","Daenerys Targaryen", date(281, 1, 1),True,15)
    add_history(2,"Daenerys is in her early teens living in exile in Essos. She remains dependent on her abusive older brother, Viserys, and is forced to marry Dothraki horselord Khal Drogo in exchange for an army for Viserys, who wishes to return to Westeros and recapture the Iron Throne.")
    add_hero("Lannister","Joffrey Baratheon", date(282, 1, 1),False,2)
    add_history(3,"Prince Joffrey Baratheon is known to the Seven Kingdoms as the eldest son and heir of King Robert I Baratheon and Queen Cersei Lannister. A member of House Baratheon of King's Landing, his siblings are Princess Myrcella and Prince Tommen.")
    add_hero("Stark","Arya Stark", date(287,1,1),True,13)
    add_history(4, "Princess Arya Stark is the third child and second daughter of Lord Eddard Stark and his wife, Lady Catelyn Stark. She is the sister of the incumbent Westerosi monarchs, Sansa, Queen in the North, and Brandon, King of the Andals and the First Men.")
    add_hero("Targaryen", "Aerys II Targaryen", date(240,1,1), False, 6)
    add_history(5,"King Aerys II Targaryen, commonly called \"the Mad King\", was the sixteenth member of House Targaryen to rule from the Iron Throne. Although his rule began benevolently, he succumbed to the madness caused by his incestuous lineage, and was eventually deposed by Lord Robert Baratheon in a civil war.")
    add_hero("Lannister","Tywin Lannister", date(234,1,1), False, 11)
    add_history(6,"Lord Tywin Lannister was the head of House Lannister, Lord of Casterly Rock, Warden of the West, Lord Paramount of the Westerlands, Hand of the King for three different kings, and Protector of the Realm. He was the father of Cersei, Jaime, and Tyrion Lannister, and sole grandfather of the incest-born Joffrey, Myrcella, and Tommen Baratheon.")
    add_hero("Lannister","Jaime Lannister",date(261,1,1),False,8)
    add_history(7,"Ser Jaime Lannister was the elder son of Lord Tywin Lannister, younger twin brother of Queen Cersei Lannister, and older brother of Tyrion Lannister. He was involved in an incestuous relationship with Cersei, and unknown to most, he was the biological father of her three bastard children, Joffrey, Myrcella, and Tommen, as well as her unborn child.")
    add_hero("Stark", "Eddard Stark",date(263,1,1), False, 5)
    add_history(8,"Lord Eddard Stark, also known as Ned Stark, was the head of House Stark, the Lord of Winterfell, Lord Paramount and Warden of the North, and later Hand of the King to King Robert I Baratheon. He was the older brother of Benjen, Lyanna and the younger brother of Brandon Stark. He is the father of Robb, Sansa, Arya, Bran, and Rickon by his wife, Catelyn Tully, and uncle of Jon Snow, who he raised as his bastard son.")
    add_hero("Targaryen", "Drogo",date(273,1,1),False, 9)
    add_history(9,"Khal Drogo was a chieftain of a Dothraki khalasar. He was often referred to as \"The Great Khal.\" He is also the namesake of the last living dragon in existence, Drogon, who was the personal mount of his late widow.")

    # 4 - create moto
    add_moto(1,"If I Fall, Don't Bring Me Back")
    add_moto(1,"I Do Know Some Things...")
    add_moto(1,"You All Crowned Me Your King. I Never Wanted It...")
    add_moto(2,"They can live in my new world, or they can die in their old one")
    add_moto(2,"I will answer injustice with justice")
    add_moto(2,"My reign has just begun")
    add_moto(3,"I cannot abide the wailing of women")
    add_moto(3,"I am the king! I will punish you!")
    add_moto(3,"Will you forgive me for my rudeness?")
    add_moto(4,"Fear cuts deeper than swords")
    add_moto(4,"Not today")
    add_moto(4,"A girl has no name")
    add_moto(5,"I want him dead, the traitor.")
    add_moto(5,"Burn them all! BURN THEM ALL!")
    add_moto(5,"I want his head, you'll bring me his head, or you'll burn with all the rest.")
    add_moto(6,"A Lion Doesn't Concern Himself With The Opinions Of The Sheep")
    add_moto(6,"Why Is He Still Alive?")
    add_moto(6,"You Really Think A Crown Gives You Power?")
    add_moto(7, "By What Right Does The Wolf Judge The Lion?")
    add_moto(7, "The Things I Do For Love.")
    add_moto(7, "People Have Been Swinging At Me For Years, But They Always Seem To Miss...")
    add_moto(8, "The winters are hard but the Starks will endure. We always have.")
    add_moto(8, "We've come to a dangerous place. We can't afford to fight a war amongst ourselves.")
    add_moto(8, "The man who passes the sentence should swing the sword")
    add_moto(9, "You are no king.")
    add_moto(9, "A Crown For A King!")
    add_moto(9, "No!")

    for i in range(10):
        add_random_battle()